### ISSUE TITLE
SSH missing

### ISSUE THREAD

**Issue by goatchurchprime** [DynamicDevices/ming#2]
Can't login and fix things (like time)

**Comment by goatchurchprime** [comment]
Alex has ordered this: https://www.amazon.co.uk/DS3231-RTC-MODULE-RASPBERRY-PI/dp/B01I1I8HY8

Though there still needs to be a provision to set the time initially.

**Comment by ajlennon** [comment]
Well SSH is enabled or disabled based on the root image download. So if we use a standard RPIv3 DEBUG image from Balena it will be enabled.

**Comment by MatthewCroughan** [comment]
The idea is that you don't need to SSH into the box, and as such it is disabled for security reasons like an appliance would be. The setup is as if it were an appliance, what is it exactly that you needed SSH for? @goatchurchprime

**Comment by ajlennon** [comment]
There are two types of image  you can use with Balena - Prod and Dev. 

If you use a Dev image then there is open access for root via SSH on port 22222

e.g. `ssh root@e844144.local -p 22222`

If you use a Prod image then by design there is no access locally via SSH although you can access the device via SSH proxied through the Balena Server
